spring.jackson.serialization.INDENT_OUTPUT: true

logging.level:
  org.springframework: WARN
  io.undertow: ERROR
  org.xnio: ERROR
  org.apache: ERROR
  org.hibernate: WARN
  org.hibernate.SQL: DEBUG
  org.hibernate.type.descriptor.sql.BasicBinder: TRACE

spring:

